import { AlertTriangle, CheckCircle2, XCircle, Info, ShieldAlert, Zap, Landmark, Scale, ExternalLink } from "lucide-react";

export const metadata = {
  title: "Important Disclaimer | Foxplayer Algo Technologies",
  description: "Important safety and regulatory information regarding Foxplayer Algo Technologies.",
};

export default function DisclaimerPage() {
  return (
    <main className="bg-background pt-32 pb-24 px-6">
      <div className="max-w-4xl mx-auto">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-500 text-xs font-bold uppercase tracking-widest mb-8">
          <AlertTriangle className="w-3.5 h-3.5" /> Important Regulatory Information
        </div>
        
        <h1 className="text-4xl md:text-6xl font-extrabold text-white mb-8 leading-tight">
          ⚠️ IMPORTANT DISCLAIMER
        </h1>
        
        <p className="text-xl text-white/70 mb-12 border-l-4 border-amber-500 pl-8 py-2 italic leading-relaxed">
          FoxPlayer is a software automation tool ONLY. It is NOT a trading platform, advisory service, or financial service provider.
        </p>

        <div className="space-y-16">
          {/* Section 1 */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-3">
              <span className="text-primary">1.</span> What FoxPlayer Is NOT
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {[
                "NOT a registered trading or investment advisory platform",
                "NOT registered with SEBI (Securities and Exchange Board of India)",
                "NOT a broker or financial institution",
                "NOT providing buy/sell recommendations",
                "NOT providing financial or investment advice",
                "NOT guaranteeing profits or returns",
                "NOT managing user funds or accounts"
              ].map((item) => (
                <div key={item} className="flex items-start gap-3 p-4 rounded-xl bg-white/[0.02] border border-white/5">
                  <XCircle className="w-5 h-5 text-red-500 shrink-0 mt-0.5" />
                  <span className="text-white/60 text-sm leading-relaxed">{item}</span>
                </div>
              ))}
            </div>
          </section>

          {/* Section 2 */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-3">
              <span className="text-primary">2.</span> What FoxPlayer Is
            </h2>
            <p className="text-white/50 mb-6 italic">FoxPlayer is ONLY a technology bridge that:</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {[
                "Receives signals generated by YOU (via TradingView, AmiBroker, etc.)",
                "Forwards those signals to YOUR broker for execution",
                "Automates the execution process",
                "Helps eliminate manual entry errors"
              ].map((item) => (
                <div key={item} className="flex items-start gap-3 p-4 rounded-xl bg-primary/5 border border-primary/10">
                  <CheckCircle2 className="w-5 h-5 text-emerald-500 shrink-0 mt-0.5" />
                  <span className="text-white/80 text-sm leading-relaxed">{item}</span>
                </div>
              ))}
            </div>
          </section>

          {/* Section 3-10 Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12 border-t border-white/5 pt-16">
            <section>
              <h3 className="text-xl font-bold text-white mb-4 italic underline decoration-primary/30">3. User Responsibility</h3>
              <p className="text-sm text-white/50 leading-relaxed space-y-4">
                By using FoxPlayer, you acknowledge and agree that:<br /><br />
                • YOU are responsible for all trading decisions<br />
                • YOU are responsible for all profits and losses<br />
                • YOU must generate your own trading signals (via TradingView, AmiBroker, etc.)<br />
                • YOU must understand the risks involved in trading<br />
                • YOU assume 100% financial risk from trading
              </p>
            </section>

            <section>
              <h3 className="text-xl font-bold text-white mb-4 italic underline decoration-primary/30">4. No Financial Advice</h3>
              <p className="text-sm text-white/50 leading-relaxed">
                Nothing on FoxPlayer website or in our communications should be construed as:<br /><br />
                • Financial advice<br />
                • Investment recommendations<br />
                • Trading advice<br />
                • Legal advice<br />
                • Tax advice
              </p>
            </section>

            <section>
              <h3 className="text-xl font-bold text-white mb-4 italic underline decoration-primary/30">5. Risk Acknowledgment</h3>
              <p className="text-sm text-white/50 leading-relaxed">
                Trading and investing in financial markets involves substantial risk of loss. Past performance does not indicate future results. You must:<br /><br />
                • Understand the risks of the instruments you&apos;re trading<br />
                • Only trade with capital you can afford to lose<br />
                • Implement proper risk management<br />
                • Consult with a qualified financial advisor if needed
              </p>
            </section>

            <section>
              <h3 className="text-xl font-bold text-white mb-4 italic underline decoration-primary/30">6. Technical Risks</h3>
              <p className="text-sm text-white/50 leading-relaxed">
                While we maintain 99.9% uptime, FoxPlayer is not responsible for:<br /><br />
                • Network or internet outages<br />
                • Broker system failures<br />
                • Market-related execution delays<br />
                • Slippage or price gaps<br />
                • Broker-side rejections
              </p>
            </section>

            <section>
              <h3 className="text-xl font-bold text-white mb-4 italic underline decoration-primary/30">7. Regulatory Compliance</h3>
              <p className="text-sm text-white/50 leading-relaxed">
                • FoxPlayer is NOT regulated by SEBI, RBI, or NISM<br />
                • FoxPlayer does NOT fall under SEBI guidelines for trading/advisory platforms<br />
                • Users are responsible for compliance with applicable trading laws<br />
                • Each user must ensure their trading activity complies with Indian law
              </p>
            </section>

            <section>
              <h3 className="text-xl font-bold text-white mb-4 italic underline decoration-primary/30">8. No Endorsement</h3>
              <p className="text-sm text-white/50 leading-relaxed">
                FoxPlayer does NOT endorse any trading strategy or signal provider. We are a neutral technology platform.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-bold text-white mb-4 italic underline decoration-primary/30">9. Third-Party Responsibility</h3>
              <p className="text-sm text-white/50 leading-relaxed">
                FoxPlayer is not responsible for:<br /><br />
                • Signal quality from TradingView or AmiBroker<br />
                • Broker execution or service quality<br />
                • Third-party integrations
              </p>
            </section>

            <section>
              <h3 className="text-xl font-bold text-white mb-4 italic underline decoration-primary/30">10. Limitation of Liability</h3>
              <p className="text-sm text-white/50 leading-relaxed">
                To the maximum extent permitted by law, FoxPlayer and its owners, employees, and agents shall NOT be liable for:<br /><br />
                • Any direct, indirect, incidental, or consequential damages<br />
                • Loss of profits, data, or income<br />
                • Trading losses or financial damages<br />
                • Any claims arising from use of FoxPlayer
              </p>
            </section>
          </div>

          <div className="p-8 rounded-3xl bg-white/[0.02] border border-white/5 mt-12">
            <h3 className="text-xl font-bold text-white mb-4">11. Indemnification</h3>
            <p className="text-sm text-white/50 mb-8 leading-relaxed">
              You agree to indemnify and hold harmless FoxPlayer from any claims, damages, or losses arising from your use of our service or your trading activity.
            </p>

            <h3 className="text-xl font-bold text-white mb-4">12. Contact & Clarifications</h3>
            <p className="text-sm text-white/50 mb-4">
              If you have questions about what FoxPlayer does or does not do, contact us immediately at:
            </p>
            <a href="mailto:raffiq_sr@yahoo.co.in" className="text-primary font-bold text-lg hover:underline decoration-primary/30">
              raffiq_sr@yahoo.co.in
            </a>
          </div>

          <div className="text-center pt-12 border-t border-white/5">
            <p className="text-white/30 text-xs italic">
              By using FoxPlayer, you acknowledge that you have read, understood, and agree to all terms in this disclaimer.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
